#! /bin/sh

if [ ! -f /etc/part_was_expanded ]
then
    touch /etc/part_was_expanded

    fdisk /dev/mmcblk0 <<EOF
d
4
n
p
804864

t
4
c
w
EOF

    sync
    poweroff -f

fi

if [ ! -f /etc/fs_was_expanded ]
then
    touch /etc/fs_was_expanded
    
    mkdosfs -v /dev/mmcblk0p4


    # poweroff
    sync
    poweroff -f
fi